apiVersion: v1
kind: Service
metadata:
  name: {{ include "soma.gatewayName" . }}
  labels:
    {{- include "soma.labels" (dict "root" . "component" "gateway") | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "soma.selectorLabels" (dict "root" . "component" "gateway") | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.ports.s3 }}
      targetPort: s3
      protocol: TCP
    - name: admin
      port: {{ .Values.ports.admin }}
      targetPort: admin
      protocol: TCP
