{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soma.fullname" . }}
  labels:
    {{- include "soma.labels" (dict "root" . "component" "gateway") | nindent 4 }}
type: Opaque
stringData:
  SOMA_ACCESS_KEY: {{ .Values.credentials.accessKey | quote }}
  SOMA_SECRET_KEY: {{ .Values.credentials.secretKey | quote }}
  {{- if and .Values.encryption.enabled .Values.encryption.masterKey }}
  SOMA_MASTER_KEY: {{ .Values.encryption.masterKey | quote }}
  {{- end }}
{{- end }}
